version: '2'

services:
    web:
        build: .
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/tweety_dev_db
            - DJANGO_SECRET_KEY=asnjdnasj34*-asdnasf12
        volumes:
            - .:/tweety
        ports:
            - "8000:8000"
        command: python3 manage.py runserver 0.0.0.0:8000
        depends_on:
            - db

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tweety_dev_db
